/*
 * Bio Translator Knowledge Beacon API
 * This is the Translator Knowledge Beacon web service application programming interface (API) 
 *
 * OpenAPI spec version: 1.1.1
 * Contact: richard@starinformatics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package bio.knowledge.client.api;

import bio.knowledge.client.ApiException;
import bio.knowledge.client.model.BeaconStatement;
import bio.knowledge.client.model.BeaconStatementWithDetails;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for StatementsApi
 */
@Ignore
public class StatementsApiTest {

    private final StatementsApi api = new StatementsApi();

    
    /**
     * 
     *
     * Retrieves a details relating to a specified concept-relationship statement include &#39;is_defined_by and &#39;provided_by&#39; provenance; extended edge properties exported as tag &#x3D; value; and any associated annotations (publications, etc.)  cited as evidence for the given statement. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStatementDetailsTest() throws ApiException {
        String statementId = null;
        List<String> keywords = null;
        Integer size = null;
        BeaconStatementWithDetails response = api.getStatementDetails(statementId, keywords, size);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Given a specified set of [CURIE-encoded](https://www.w3.org/TR/curie/)  source (&#39;s&#39;) concept identifiers,  retrieves a list of relationship statements where either the subject or object concept matches any of the input &#39;source&#39; concepts provided.  Optionally, a set of target (&#39;t&#39;) concept  identifiers may also be given, in which case a member of the &#39;target&#39; identifier set should match the concept opposing the &#39;source&#39; in the  statement, that is, if the&#39;source&#39; matches a subject, then the  &#39;target&#39; should match the object of a given statement (or vice versa). 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStatementsTest() throws ApiException {
        List<String> s = null;
        String edgeLabel = null;
        String relation = null;
        List<String> t = null;
        List<String> keywords = null;
        List<String> categories = null;
        Integer size = null;
        List<BeaconStatement> response = api.getStatements(s, edgeLabel, relation, t, keywords, categories, size);

        // TODO: test validations
    }
    
}
