jenkins:
  systemMessage: "Validator Jenkins Pipeline"
jobs:
  - script: >
      multibranchPipelineJob('jenkins-validator') {
        branchSources {
          git {
            id('123456789') // IMPORTANT: use a constant and unique identifier
            remote('https://github.com/lhannest/jenkins-validator.git')
          }
        }
        orphanedItemStrategy {
          discardOldItems {
            numToKeep(1)
          }
        }
        triggers {
          periodic(5)
        }
      }
