jenkins:
  systemMessage: "Simple example"
jobs:
  - script: >
      multibranchPipelineJob('image-jenkins') {
        branchSources {
          git {
            id('123456789') // IMPORTANT: use a constant and unique identifier
            remote('https://github.com/lhannest/jenkins-junit.git')
          }
        }
        orphanedItemStrategy {
          discardOldItems {
            numToKeep(1)
          }
        }
        triggers {
          periodic(5)
        }
      }
