/*
 * Bio Translator Knowledge Beacon API
 * This is the Translator Knowledge Beacon web service application programming interface (API) 
 *
 * OpenAPI spec version: 1.1.1
 * Contact: richard@starinformatics.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package bio.knowledge.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ExactMatchResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-28T22:55:08.857Z")
public class ExactMatchResponse {
  @SerializedName("id")
  private String id = null;

  @SerializedName("within_domain")
  private Boolean withinDomain = null;

  @SerializedName("has_exact_matches")
  private List<String> hasExactMatches = new ArrayList<String>();

  public ExactMatchResponse id(String id) {
    this.id = id;
    return this;
  }

   /**
   * A given [CURIE](https://www.w3.org/TR/curie/) identifier. 
   * @return id
  **/
  @ApiModelProperty(example = "null", value = "A given [CURIE](https://www.w3.org/TR/curie/) identifier. ")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public ExactMatchResponse withinDomain(Boolean withinDomain) {
    this.withinDomain = withinDomain;
    return this;
  }

   /**
   * True if the knowledge source is aware of this identifier, and has the capacity to return the identified concept. Otherwise, false. 
   * @return withinDomain
  **/
  @ApiModelProperty(example = "null", value = "True if the knowledge source is aware of this identifier, and has the capacity to return the identified concept. Otherwise, false. ")
  public Boolean getWithinDomain() {
    return withinDomain;
  }

  public void setWithinDomain(Boolean withinDomain) {
    this.withinDomain = withinDomain;
  }

  public ExactMatchResponse hasExactMatches(List<String> hasExactMatches) {
    this.hasExactMatches = hasExactMatches;
    return this;
  }

  public ExactMatchResponse addHasExactMatchesItem(String hasExactMatchesItem) {
    this.hasExactMatches.add(hasExactMatchesItem);
    return this;
  }

   /**
   * List of [CURIE](https://www.w3.org/TR/curie/) identifiers of a exactly matching concepts. 
   * @return hasExactMatches
  **/
  @ApiModelProperty(example = "null", value = "List of [CURIE](https://www.w3.org/TR/curie/) identifiers of a exactly matching concepts. ")
  public List<String> getHasExactMatches() {
    return hasExactMatches;
  }

  public void setHasExactMatches(List<String> hasExactMatches) {
    this.hasExactMatches = hasExactMatches;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExactMatchResponse exactMatchResponse = (ExactMatchResponse) o;
    return Objects.equals(this.id, exactMatchResponse.id) &&
        Objects.equals(this.withinDomain, exactMatchResponse.withinDomain) &&
        Objects.equals(this.hasExactMatches, exactMatchResponse.hasExactMatches);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, withinDomain, hasExactMatches);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExactMatchResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    withinDomain: ").append(toIndentedString(withinDomain)).append("\n");
    sb.append("    hasExactMatches: ").append(toIndentedString(hasExactMatches)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

